version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/www:cached

    ports:
      - "41062:80"



  db:
    image: mariadb:10.4
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pk515601
      MYSQL_DATABASE: db_user_system
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: pk515601

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "41063:80"
    environment:
      #- PMA_ARBITRARY=1
      PMA_HOST: db
      PMA_USER: mariadb
      PMA_PASSWORD: pk515601
      

  
volumes:
  mariadb-data:
